class AsmaulHusna {
  final int number;
  final String latin;
  final String arabic;
  final String translation;

  const AsmaulHusna({
    required this.number,
    required this.latin,
    required this.arabic,
    required this.translation,
  });
}

class AsmaulHusnaHelper {
  static const List<AsmaulHusna> names = [
    AsmaulHusna(number: 1, latin: "Ar-Rahman", arabic: "الرحمن", translation: "Yang Maha Pengasih"),
    AsmaulHusna(number: 2, latin: "Ar-Rahim", arabic: "الرحيم", translation: "Yang Maha Penyayang"),
    AsmaulHusna(number: 3, latin: "Al-Malik", arabic: "الملك", translation: "Yang Maha Merajai"),
    AsmaulHusna(number: 4, latin: "Al-Quddus", arabic: "القدوس", translation: "Yang Maha Suci"),
    AsmaulHusna(number: 5, latin: "As-Salam", arabic: "السلام", translation: "Yang Maha Memberi Kesejahteraan"),
    AsmaulHusna(number: 6, latin: "Al-Mu'min", arabic: "المؤمن", translation: "Yang Maha Memberi Keamanan"),
    AsmaulHusna(number: 7, latin: "Al-Muhaimin", arabic: "المهيمن", translation: "Yang Maha Pemelihara"),
    AsmaulHusna(number: 8, latin: "Al-Aziz", arabic: "العزيز", translation: "Yang Maha Perkasa"),
    AsmaulHusna(number: 9, latin: "Al-Jabbar", arabic: "الجبار", translation: "Yang Memiliki Mutlak Kegagahan"),
    AsmaulHusna(number: 10, latin: "Al-Mutakabbir", arabic: "المتكبر", translation: "Yang Maha Megah"),
    AsmaulHusna(number: 11, latin: "Al-Khaliq", arabic: "الخالق", translation: "Yang Maha Pencipta"),
    AsmaulHusna(number: 12, latin: "Al-Bari'", arabic: "البارئ", translation: "Yang Maha Melepaskan"),
    AsmaulHusna(number: 13, latin: "Al-Musawwir", arabic: "المصور", translation: "Yang Maha Membentuk Rupa"),
    AsmaulHusna(number: 14, latin: "Al-Ghaffar", arabic: "الغفار", translation: "Yang Maha Pengampun"),
    AsmaulHusna(number: 15, latin: "Al-Qahhar", arabic: "الهار", translation: "Yang Maha Menaklukkan"),
    AsmaulHusna(number: 16, latin: "Al-Wahhab", arabic: "الوهاب", translation: "Yang Maha Pemberi Karunia"),
    AsmaulHusna(number: 17, latin: "Ar-Razzaq", arabic: "الرزاق", translation: "Yang Maha Pemberi Rezeki"),
    AsmaulHusna(number: 18, latin: "Al-Fattah", arabic: "الفتاح", translation: "Yang Maha Pembuka Rahmat"),
    AsmaulHusna(number: 19, latin: "Al-Alim", arabic: "العليم", translation: "Yang Maha Mengetahui"),
    AsmaulHusna(number: 20, latin: "Al-Qabid", arabic: "القابض", translation: "Yang Maha Menyempitkan"),
    AsmaulHusna(number: 21, latin: "Al-Basit", arabic: "الباسط", translation: "Yang Maha Melapangkan"),
    AsmaulHusna(number: 22, latin: "Al-Khafid", arabic: "الخافض", translation: "Yang Maha Merendahkan"),
    AsmaulHusna(number: 23, latin: "Ar-Rafi'", arabic: "الرافع", translation: "Yang Maha Meninggikan"),
    AsmaulHusna(number: 24, latin: "Al-Mu'izz", arabic: "المعز", translation: "Yang Maha Memuliakan"),
    AsmaulHusna(number: 25, latin: "Al-Mudhill", arabic: "المذل", translation: "Yang Maha Menghinakan"),
    AsmaulHusna(number: 26, latin: "As-Sami'", arabic: "السميع", translation: "Yang Maha Mendengar"),
    AsmaulHusna(number: 27, latin: "Al-Basir", arabic: "البصير", translation: "Yang Maha Melihat"),
    AsmaulHusna(number: 28, latin: "Al-Hakam", arabic: "الحكم", translation: "Yang Maha Menetapkan"),
    AsmaulHusna(number: 29, latin: "Al-Adl", arabic: "العدل", translation: "Yang Maha Adil"),
    AsmaulHusna(number: 30, latin: "Al-Latif", arabic: "اللطيف", translation: "Yang Maha Lembut"),
    AsmaulHusna(number: 31, latin: "Al-Khabir", arabic: "الخبير", translation: "Yang Maha Mengenal"),
    AsmaulHusna(number: 32, latin: "Al-Halim", arabic: "الحليم", translation: "Yang Maha Penyantun"),
    AsmaulHusna(number: 33, latin: "Al-Azim", arabic: "العظيم", translation: "Yang Maha Agung"),
    AsmaulHusna(number: 34, latin: "Al-Ghafur", arabic: "الغفور", translation: "Yang Maha Pengampun"),
    AsmaulHusna(number: 35, latin: "As-Syakur", arabic: "الشكور", translation: "Yang Maha Menerima Syukur"),
    AsmaulHusna(number: 36, latin: "Al-Aliy", arabic: "العلي", translation: "Yang Maha Tinggi"),
    AsmaulHusna(number: 37, latin: "Al-Kabir", arabic: "الكبير", translation: "Yang Maha Besar"),
    AsmaulHusna(number: 38, latin: "Al-Hafiz", arabic: "الحفيظ", translation: "Yang Maha Memelihara"),
    AsmaulHusna(number: 39, latin: "Al-Muqit", arabic: "المقيت", translation: "Yang Maha Pemberi Kecukupan"),
    AsmaulHusna(number: 40, latin: "Al-Hasib", arabic: "الحسيب", translation: "Yang Maha Pembuat Perhitungan"),
    AsmaulHusna(number: 41, latin: "Al-Jalil", arabic: "الجليل", translation: "Yang Maha Luhur"),
    AsmaulHusna(number: 42, latin: "Al-Karim", arabic: "الكريم", translation: "Yang Maha Mulia"),
    AsmaulHusna(number: 43, latin: "Ar-Raqib", arabic: "الرقيب", translation: "Yang Maha Mengawasi"),
    AsmaulHusna(number: 44, latin: "Al-Mujib", arabic: "المجيب", translation: "Yang Maha Mengabulkan"),
    AsmaulHusna(number: 45, latin: "Al-Wasi'", arabic: "الواسع", translation: "Yang Maha Luas"),
    AsmaulHusna(number: 46, latin: "Al-Hakim", arabic: "الحكيم", translation: "Yang Maha Bijaksana"),
    AsmaulHusna(number: 47, latin: "Al-Wadud", arabic: "الودود", translation: "Yang Maha Mengasihi"),
    AsmaulHusna(number: 48, latin: "Al-Majid", arabic: "المجيد", translation: "Yang Maha Mulia"),
    AsmaulHusna(number: 49, latin: "Al-Ba'ith", arabic: "الباعث", translation: "Yang Maha Membangkitkan"),
    AsmaulHusna(number: 50, latin: "As-Syahid", arabic: "الشهيد", translation: "Yang Maha Menyaksikan"),
    AsmaulHusna(number: 51, latin: "Al-Haqq", arabic: "الحق", translation: "Yang Maha Benar"),
    AsmaulHusna(number: 52, latin: "Al-Wakil", arabic: "الوكيل", translation: "Yang Maha Memelihara"),
    AsmaulHusna(number: 53, latin: "Al-Qawiyy", arabic: "القوي", translation: "Yang Maha Kuat"),
    AsmaulHusna(number: 54, latin: "Al-Matin", arabic: "المتين", translation: "Yang Maha Kokoh"),
    AsmaulHusna(number: 55, latin: "Al-Waliyy", arabic: "الولي", translation: "Yang Maha Melindungi"),
    AsmaulHusna(number: 56, latin: "Al-Hamid", arabic: "الحميد", translation: "Yang Maha Terpuji"),
    AsmaulHusna(number: 57, latin: "Al-Muhsi", arabic: "المحصي", translation: "Yang Maha Mengalkulasi"),
    AsmaulHusna(number: 58, latin: "Al-Mubdi'", arabic: "المبدئ", translation: "Yang Maha Memulai"),
    AsmaulHusna(number: 59, latin: "Al-Mu'id", arabic: "المعيد", translation: "Yang Maha Mengembalikan Kehidupan"),
    AsmaulHusna(number: 60, latin: "Al-Muhyi", arabic: "المحيي", translation: "Yang Maha Menghidupkan"),
    AsmaulHusna(number: 61, latin: "Al-Mumit", arabic: "المميت", translation: "Yang Maha Mematikan"),
    AsmaulHusna(number: 62, latin: "Al-Hayyu", arabic: "الحي", translation: "Yang Maha Hidup"),
    AsmaulHusna(number: 63, latin: "Al-Qayyum", arabic: "القيوم", translation: "Yang Maha Mandiri"),
    AsmaulHusna(number: 64, latin: "Al-Wajid", arabic: "الواجد", translation: "Yang Maha Penemu"),
    AsmaulHusna(number: 65, latin: "Al-Majid", arabic: "الماجد", translation: "Yang Maha Mulia"),
    AsmaulHusna(number: 66, latin: "Al-Wahid", arabic: "الواحد", translation: "Yang Maha Tunggal"),
    AsmaulHusna(number: 67, latin: "Al-Ahad", arabic: "الأحد", translation: "Yang Maha Esa"),
    AsmaulHusna(number: 68, latin: "As-Samad", arabic: "الصمد", translation: "Yang Maha Dibutuhkan"),
    AsmaulHusna(number: 69, latin: "Al-Qadir", arabic: "القادر", translation: "Yang Maha Menentukan"),
    AsmaulHusna(number: 70, latin: "Al-Muqtadir", arabic: "المقتدر", translation: "Yang Maha Berkuasa"),
    AsmaulHusna(number: 71, latin: "Al-Muqaddim", arabic: "المقدم", translation: "Yang Maha Mendahulukan"),
    AsmaulHusna(number: 72, latin: "Al-Mu'akhkhir", arabic: "المؤخر", translation: "Yang Maha Mengakhirkan"),
    AsmaulHusna(number: 73, latin: "Al-Awwal", arabic: "الأول", translation: "Yang Maha Awal"),
    AsmaulHusna(number: 74, latin: "Al-Akhir", arabic: "الآخر", translation: "Yang Maha Akhir"),
    AsmaulHusna(number: 75, latin: "Az-Zahir", arabic: "الظاهر", translation: "Yang Maha Nyata"),
    AsmaulHusna(number: 76, latin: "Al-Batin", arabic: "الباطن", translation: "Yang Maha Gaib"),
    AsmaulHusna(number: 77, latin: "Al-Wali", arabic: "الوالي", translation: "Yang Maha Memerintah"),
    AsmaulHusna(number: 78, latin: "Al-Muta'ali", arabic: "المتعالي", translation: "Yang Maha Tinggi"),
    AsmaulHusna(number: 79, latin: "Al-Barr", arabic: "البر", translation: "Yang Maha Penderma"),
    AsmaulHusna(number: 80, latin: "At-Tawwab", arabic: "التواب", translation: "Yang Maha Penerima Tobat"),
    AsmaulHusna(number: 81, latin: "Al-Muntaqim", arabic: "المنتقم", translation: "Yang Maha Pemberi Balasan"),
    AsmaulHusna(number: 82, latin: "Al-Afuww", arabic: "العفو", translation: "Yang Maha Pemaaf"),
    AsmaulHusna(number: 83, latin: "Ar-Ra'uf", arabic: "الرؤوف", translation: "Yang Maha Pengasuh"),
    AsmaulHusna(number: 84, latin: "Malikul-Mulk", arabic: "مالك الملك", translation: "Yang Maha Penguasa Kerajaan"),
    AsmaulHusna(number: 85, latin: "Dzul-Jalali Wal-Ikram", arabic: "ذو الجلال والإكرام", translation: "Pemilik Keagungan dan Kemuliaan"),
    AsmaulHusna(number: 86, latin: "Al-Muqsit", arabic: "المقسط", translation: "Yang Maha Pemberi Keadilan"),
    AsmaulHusna(number: 87, latin: "Al-Jami'", arabic: "الجامع", translation: "Yang Maha Mengumpulkan"),
    AsmaulHusna(number: 88, latin: "Al-Ghaniyy", arabic: "الغني", translation: "Yang Maha Kaya"),
    AsmaulHusna(number: 89, latin: "Al-Mughni", arabic: "المغني", translation: "Yang Maha Pemberi Kekayaan"),
    AsmaulHusna(number: 90, latin: "Al-Mani'", arabic: "المانع", translation: "Yang Maha Mencegah"),
    AsmaulHusna(number: 91, latin: "Ad-Darr", arabic: "الضار", translation: "Yang Maha Penimpa Kemudaratan"),
    AsmaulHusna(number: 92, latin: "An-Nafi'", arabic: "النافع", translation: "Yang Maha Pemberi Manfaat"),
    AsmaulHusna(number: 93, latin: "An-Nur", arabic: "النور", translation: "Yang Maha Bercahaya"),
    AsmaulHusna(number: 94, latin: "Al-Hadi", arabic: "الهادي", translation: "Yang Maha Pemberi Petunjuk"),
    AsmaulHusna(number: 95, latin: "Al-Badi'", arabic: "البديع", translation: "Yang Maha Pencipta Tiada Bandingan"),
    AsmaulHusna(number: 96, latin: "Al-Baqi", arabic: "الباقي", translation: "Yang Maha Kekal"),
    AsmaulHusna(number: 97, latin: "Al-Warith", arabic: "الوارث", translation: "Yang Maha Pewaris"),
    AsmaulHusna(number: 98, latin: "Ar-Rasyid", arabic: "الرشيد", translation: "Yang Maha Pandai"),
    AsmaulHusna(number: 99, latin: "As-Sabur", arabic: "الصبور", translation: "Yang Maha Penyabar"),
  ];
}
