include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    use_build_context_synchronously: error
    discarded_futures: error
    unawaited_futures: error
    deprecated_member_use: warning

linter:
  rules:
    - use_build_context_synchronously
    - discarded_futures
    - unawaited_futures
